const styles = {
  container: {
    fontFamily: 'Inter, sans-serif',
    color: '#f9fafb',
    minHeight: '100vh',
    padding: '0 0 48px',
    background: 'radial-gradient(circle at 20% 20%, #374151 0%, #111827 45%, #030712 100%)',
  },
  navbar: {
    position: 'sticky',
    top: 0,
    zIndex: 60,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 24,
    flexWrap: 'wrap',
    padding: '18px clamp(16px, 4vw, 44px)',
    background: 'rgba(2, 6, 23, 0.82)',
    borderBottom: '1px solid rgba(148, 163, 184, 0.18)',
    backdropFilter: 'blur(12px)',
    animation: 'slideDown 0.45s ease both',
  },
  navbarMobile: {
    gap: 8,
    padding: '10px 12px',
  },
  navBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  navLogo: {
    fontSize: '1.85rem',
    filter: 'drop-shadow(0 10px 16px rgba(248, 113, 113, 0.55))',
    background: 'linear-gradient(140deg, rgba(239, 68, 68, 0.24), rgba(14, 165, 233, 0.26))',
    border: '1px solid rgba(148, 163, 184, 0.32)',
    borderRadius: 12,
    padding: '4px 8px',
  },
  navBrandTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  navBrandTitle: {
    margin: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    fontWeight: 900,
    letterSpacing: '0.02em',
    fontSize: '1.24rem',
    textTransform: 'uppercase',
  },
  navBrandTitleCin: {
    color: '#f8fafc',
    textShadow: '0 0 18px rgba(248, 113, 113, 0.35)',
  },
  navBrandTitlePulse: {
    background: 'linear-gradient(90deg, #f43f5e 0%, #f59e0b 45%, #38bdf8 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    textShadow: '0 0 18px rgba(14, 165, 233, 0.35)',
  },
  navBrandSub: {
    margin: '3px 0 0',
    color: '#93c5fd',
    fontSize: '0.76rem',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  navControlRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 12,
  },
  navControlRowMobile: {
    width: '100%',
    justifyContent: 'space-between',
    gap: 8,
  },
  hero: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    margin: '44px auto 26px',
    padding: '0 16px',
    gap: 12,
    animation: 'fadeInUp 0.6s ease both',
  },
  heroMobile: {
    margin: '26px auto 18px',
    gap: 10,
  },
  heroBadge: {
    border: '1px solid rgba(250, 204, 21, 0.45)',
    color: '#fef08a',
    borderRadius: 999,
    padding: '6px 16px',
    background: 'rgba(250, 204, 21, 0.08)',
    fontSize: '0.84rem',
    letterSpacing: '0.03em',
    textTransform: 'uppercase',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },
  heroBadgeMobile: {
    fontSize: '0.72rem',
    padding: '5px 10px',
    letterSpacing: '0.02em',
  },
  heroBadgeDot: {
    width: 9,
    height: 9,
    borderRadius: '50%',
    background: '#22c55e',
    boxShadow: '0 0 0 0 rgba(34, 197, 94, 0.75)',
    animation: 'pulseDot 1.4s infinite',
  },
  title: {
    margin: 0,
    fontSize: 'clamp(2rem, 4vw, 3.2rem)',
    fontWeight: 900,
    background: 'linear-gradient(90deg, #f87171 0%, #facc15 45%, #38bdf8 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    letterSpacing: '0.01em',
    animation: 'fadeInUp 0.8s ease both',
  },
  titleMobile: {
    fontSize: 'clamp(1.35rem, 7vw, 1.9rem)',
    padding: '0 8px',
  },
  tagline: {
    fontSize: '1.08rem',
    color: '#d1d5db',
    margin: 0,
    maxWidth: 680,
    lineHeight: 1.65,
    animation: 'fadeInUp 1s ease both',
  },
  nav: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  navMobile: {
    gap: 6,
  },
  authGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  authGroupMobile: {
    gap: 6,
  },
  button: {
    padding: '10px 18px',
    background: 'rgba(255, 255, 255, 0.06)',
    color: '#f8fafc',
    border: '1px solid rgba(148, 163, 184, 0.4)',
    borderRadius: 999,
    fontSize: '0.95rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    outline: 'none',
    whiteSpace: 'nowrap',
  },
  buttonMobile: {
    padding: '6px 10px',
    fontSize: '0.78rem',
  },
  activeButton: {
    background: 'linear-gradient(90deg, #dc2626, #f97316)',
    border: '1px solid rgba(248, 113, 113, 0.9)',
    color: '#fff',
    boxShadow: '0 10px 18px rgba(220, 38, 38, 0.28)',
  },
  authButton: {
    border: '1px solid rgba(250, 204, 21, 0.5)',
    background: 'rgba(30, 41, 59, 0.72)',
  },
  userBox: {
    background: 'rgba(30, 41, 59, 0.9)',
    color: '#fef08a',
    borderRadius: 999,
    padding: '9px 16px',
    fontWeight: 700,
    fontSize: '0.95rem',
    letterSpacing: 0.2,
    border: '1px solid rgba(250, 204, 21, 0.4)',
    boxShadow: '0 8px 14px rgba(2, 6, 23, 0.34)',
    display: 'flex',
    alignItems: 'center',
  },
  filterSection: {
    margin: '0 auto 30px',
    width: 'min(980px, calc(100% - 30px))',
    animation: 'fadeInUp 0.8s ease both',
    borderRadius: 16,
    border: '1px solid rgba(125, 211, 252, 0.22)',
    background: 'linear-gradient(150deg, rgba(15, 23, 42, 0.86), rgba(30, 41, 59, 0.74))',
    boxShadow: '0 14px 24px rgba(2, 6, 23, 0.28)',
    padding: '12px 12px 14px',
  },
  filterSectionMobile: {
    width: 'calc(100% - 18px)',
    padding: '10px 8px 10px',
    borderRadius: 14,
  },
  filterTitle: {
    margin: '0 0 10px',
    fontSize: '0.78rem',
    color: '#bfdbfe',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    fontWeight: 800,
  },
  filterHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  filterHeaderRowMobile: {
    marginBottom: 8,
  },
  filterControls: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 10,
  },
  filterControlsMobile: {
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 8,
    alignItems: 'end',
  },
  filterSelectGroup: {
    display: 'grid',
    gap: 7,
    minWidth: 0,
  },
  filterSelectGroupMobile: {
    gap: 5,
  },
  filterStack: {
    display: 'grid',
    gap: 14,
  },
  filterLabel: {
    margin: 0,
    color: '#93c5fd',
    fontSize: '0.7rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    fontWeight: 800,
  },
  filterLabelMobile: {
    fontSize: '0.64rem',
    letterSpacing: '0.08em',
  },
  filterSelect: {
    width: '100%',
    borderRadius: 12,
    border: '1px solid rgba(125, 211, 252, 0.32)',
    background: '#020617',
    color: '#f1f5f9',
    padding: '10px 12px',
    fontSize: '0.88rem',
    fontWeight: 700,
    outline: 'none',
    boxShadow: 'inset 0 1px 0 rgba(148, 163, 184, 0.22)',
  },
  filterSelectMobile: {
    padding: '8px 9px',
    fontSize: '0.82rem',
    borderRadius: 10,
  },
  filterOption: {
    backgroundColor: '#000',
    color: '#f8fafc',
  },
  filterToggleButton: {
    borderRadius: 999,
    border: '1px solid rgba(74, 222, 128, 0.65)',
    background: 'rgba(21, 128, 61, 0.16)',
    color: '#bbf7d0',
    padding: '7px 14px',
    fontSize: '0.82rem',
    fontWeight: 700,
    letterSpacing: '0.02em',
    cursor: 'pointer',
  },
  filterRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
  },
  filterRowMobile: {
    gap: 8,
  },
  filterChip: {
    borderRadius: 999,
    border: '1px solid rgba(148, 163, 184, 0.38)',
    background: 'rgba(15, 23, 42, 0.9)',
    color: '#dbeafe',
    padding: '8px 14px',
    fontSize: '0.9rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  filterChipMobile: {
    padding: '6px 10px',
    fontSize: '0.78rem',
  },
  filterChipActive: {
    background: 'linear-gradient(90deg, #16a34a, #22c55e)',
    color: '#f0fdf4',
    border: '1px solid rgba(74, 222, 128, 0.8)',
    boxShadow: '0 8px 16px rgba(22, 163, 74, 0.3)',
  },
  input: {
    display: 'block',
    margin: '0 auto 34px',
    padding: '13px 18px',
    width: 'min(540px, calc(100% - 28px))',
    borderRadius: 14,
    border: '1px solid rgba(148, 163, 184, 0.35)',
    fontSize: '1rem',
    background: 'rgba(15, 23, 42, 0.9)',
    color: '#f8fafc',
    outline: 'none',
    boxShadow: '0 8px 14px rgba(2, 6, 23, 0.35)',
    animation: 'fadeInUp 0.35s ease both',
  },
  inputMobile: {
    margin: '0 auto 20px',
    padding: '10px 12px',
    borderRadius: 10,
    fontSize: '0.92rem',
  },
  content: {
    minHeight: 300,
  },
  loading: {
    textAlign: 'center',
    fontSize: '1.2rem',
    color: '#86efac',
    animation: 'softPulse 1.3s ease-in-out infinite',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 22,
    padding: '0 clamp(14px, 3vw, 34px)',
  },
  gridMobile: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 8,
    padding: '0 8px',
  },
  card: {
    background: 'linear-gradient(180deg, rgba(30, 41, 59, 0.96), rgba(15, 23, 42, 0.95))',
    padding: 14,
    borderRadius: 16,
    textAlign: 'center',
    boxShadow: '0 14px 24px rgba(2, 6, 23, 0.35)',
    transition: 'transform 0.2s, box-shadow 0.2s',
    outline: 'none',
    border: '1px solid rgba(148, 163, 184, 0.2)',
    animation: 'fadeInUp 0.45s ease both',
  },
  cardCompact: {
    padding: 6,
    borderRadius: 10,
  },
  image: {
    width: '100%',
    borderRadius: 12,
    marginBottom: 12,
    boxShadow: '0 6px 14px rgba(0, 0, 0, 0.3)',
  },
  imageCompact: {
    borderRadius: 8,
    marginBottom: 6,
  },
  movieTitle: {
    fontSize: '1.02rem',
    margin: '8px 0 4px',
    fontWeight: 650,
    color: '#e2e8f0',
    lineHeight: 1.35,
  },
  movieTitleCompact: {
    fontSize: '0.62rem',
    margin: '4px 0 2px',
    lineHeight: 1.2,
    minHeight: '1.2rem',
  },
  rating: {
    color: '#fca5a5',
    fontWeight: 600,
    fontSize: '0.95rem',
  },
  ratingCompact: {
    fontSize: '0.58rem',
    margin: 0,
  },
  noMovies: {
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: '1.05rem',
    gridColumn: '1/-1',
    padding: '24px 0',
  },
  loadMoreSection: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: 16,
    padding: '0 12px',
  },
  loadMoreButton: {
    minWidth: 220,
    border: '1px solid rgba(125, 211, 252, 0.56)',
    background: 'linear-gradient(90deg, rgba(8, 47, 73, 0.9), rgba(30, 64, 175, 0.9))',
    fontWeight: 700,
  },
  loadMoreButtonDisabled: {
    opacity: 0.68,
    cursor: 'not-allowed',
  },
  loadMoreDone: {
    margin: 0,
    color: '#93c5fd',
    fontSize: '0.88rem',
    fontWeight: 700,
    textAlign: 'center',
    padding: '8px 0',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    background: 'rgba(2, 6, 23, 0.75)',
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backdropFilter: 'blur(2px)',
  },
  modal: {
    background: 'linear-gradient(160deg, #0f172a, #1e293b)',
    borderRadius: 18,
    boxShadow: '0 8px 32px rgba(0,0,0,0.35)',
    padding: '36px 32px 28px 32px',
    minWidth: 320,
    maxWidth: '90vw',
    position: 'relative',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    animation: 'fadeInModal 0.4s cubic-bezier(.4,0,.2,1)',
    border: '1px solid rgba(148, 163, 184, 0.18)',
  },
  closeModal: {
    position: 'absolute',
    top: 12,
    right: 18,
    background: 'none',
    border: 'none',
    color: '#fff',
    fontSize: '2rem',
    cursor: 'pointer',
    fontWeight: 700,
    opacity: 0.7,
    transition: 'opacity 0.2s',
  },
  modalTabs: {
    display: 'flex',
    gap: 8,
    marginBottom: 8,
    width: '100%',
    justifyContent: 'center',
  },
  modalTab: {
    background: 'none',
    border: 'none',
    color: '#fff',
    fontWeight: 700,
    fontSize: '1.1rem',
    padding: '6px 18px',
    borderRadius: 12,
    cursor: 'pointer',
    transition: 'background 0.2s, color 0.2s',
  },
  activeTab: {
    background: '#dc2626',
    color: '#fff',
  },
  modalTitle: {
    fontSize: '2rem',
    fontWeight: 800,
    marginBottom: 18,
    letterSpacing: 1,
    textAlign: 'center',
  },
  modalForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    width: '100%',
    alignItems: 'center',
  },
  modalInput: {
    width: '100%',
    padding: '12px 16px',
    borderRadius: 10,
    border: 'none',
    fontSize: '1rem',
    background: '#0b1120',
    color: '#fff',
    outline: 'none',
    boxShadow: '0 1px 4px rgba(0,0,0,0.10)',
  },
  modalSubmit: {
    padding: '10px 28px',
    background: '#dc2626',
    color: '#fff',
    border: 'none',
    borderRadius: 20,
    fontSize: '1rem',
    fontWeight: 700,
    cursor: 'pointer',
    marginTop: 8,
    boxShadow: '0 2px 8px rgba(0,0,0,0.18)',
    transition: 'background 0.2s',
  },
  toast: {
    position: 'fixed',
    bottom: 32,
    left: '50%',
    transform: 'translateX(-50%)',
    background: '#0f172a',
    color: '#fff',
    padding: '16px 32px',
    borderRadius: 16,
    fontWeight: 700,
    fontSize: '1rem',
    boxShadow: '0 2px 12px rgba(0,0,0,0.18)',
    zIndex: 2000,
    cursor: 'pointer',
    animation: 'fadeInModal 0.4s cubic-bezier(.4,0,.2,1)',
    border: '1px solid rgba(148, 163, 184, 0.24)',
  },
  footer: {
    marginTop: 40,
    padding: '0 16px 16px',
  },
  footerInner: {
    maxWidth: 980,
    margin: '0 auto',
    border: '1px solid rgba(148, 163, 184, 0.2)',
    background: 'linear-gradient(180deg, rgba(15, 23, 42, 0.85), rgba(2, 6, 23, 0.92))',
    borderRadius: 18,
    textAlign: 'center',
    padding: '22px 16px',
    color: '#94a3b8',
  },
  footerTitle: {
    margin: 0,
    fontSize: '1rem',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#f8fafc',
    textTransform: 'uppercase',
  },
  footerText: {
    margin: '8px 0 0',
    fontSize: '0.92rem',
    color: '#94a3b8',
  },
  footerLink: {
    color: '#38bdf8',
    textDecoration: 'none',
    fontWeight: 700,
  },
};

export default styles;
